task: 'classification'
datadir: 'stores/blob'
numepochs: 100
earlystopping: 10
finetuneepochs: 1
logdir: 'logs'
optimizer: 
    name: 'rmsprop'
    alpha: 0.9
    initlr: 0.256
    momentum: 0.9
    weightdecay: 1e-5
lossfn: 'crossentropyloss'
pretrained: 'imagenet'
pretrainedpath: ''
batchsize: 1
imagesize: 300
tasks:
    classification:
        extractor: 'efficientnet-b3'
        numclasses: 6
        weights: []
        labelmapping: {
                      'Lesser Mousedeer': 0, 
                      'Long Tailed Macaque': 1, 
                      'Others': 2, 
                      'Sambar Deer': 3, 
                      'Spotted Whistling Duck': 4, 
                      'Wild Pig': 5
                      }      